### ISSUE TITLE
Finale Routenstruktur in Kapitel 11 aufnehmen

### ISSUE THREAD

**Issue by astrutz** [astrutz/masterthesis#23]
Die folgende Struktur soll in der Thesis als Zusammenfassung oder als Anhang eingefügt werden:

```yaml
overview
sender
  - overview
    - index: Landingpage Absender
  - capacities
    - index: Auflistung des aktuellen Aufkommens
  - priorities
    - index: Auflistung der bisherigen Prios
    - new: Formular zum Erstellen einer neuen Prio
    - show: Anzeigen der UUID nach Erstellen der Prio
recipient
  - sessions
    - new: Einloggen
    - destroy: Ausloggen
  - recipients
    - new: Formular zum Erstellen eines neuen Accounts    
    - edit: Anpassen der Regeln und Bearbeitungsleistung
  - rules
    - index: Auflistung aller Regeln 
    - new: Formular zum Erstellen einer neuen Regel
    - edit: Formular zum Ändern einer Regeln
    - destroy: Löschen einer Regel  
  - inbox
    - show: Anzeige der E-Mails innerhalb der Triage 
```
